version: "3.8"

services:
  postgres:
    image: postgres
    env_file: ./.env
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
#      - "5434:5432"
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    depends_on:
      - postgres
    image: denysshl/rick-and-morty-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
#      - "8088:8080"
      - $DEBUG_PORT:$DEBUG_PORT
#      - "5005:5005"
    environment:
      SPRING_APPLOCATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://localhost:$POSTGRES_DOCKER_PORT/$DB_NAME"
        "spring.datasource.username" : "$DB_USER",
        "spring.datasource.password" : "$DB_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
